language: python
python:
    - 3.4
    - 3.5
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - echo 'from .development import *' > vietcong/settings/local.py
script:
    coverage run --source='.' ./manage.py test
after_success:
    coveralls
